/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Juego_TicTac extends javax.swing.JFrame {

    private int jugador;//1-> O ; 2-> X

    public Juego_TicTac() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        jugador = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnjugar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));

        jPanel2.setMaximumSize(new java.awt.Dimension(600, 50));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Juego de TicTac");

        btnjugar.setText("Reiniciar");
        btnjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnjugar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnjugar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        btn1.setBackground(Color.LIGHT_GRAY);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);

        btn2.setBackground(Color.LIGHT_GRAY);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);

        btn3.setBackground(Color.LIGHT_GRAY);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);

        btn4.setBackground(Color.LIGHT_GRAY);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);

        btn5.setBackground(Color.LIGHT_GRAY);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);

        btn6.setBackground(Color.LIGHT_GRAY);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);

        btn7.setBackground(Color.LIGHT_GRAY);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);

        btn8.setBackground(Color.LIGHT_GRAY);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);

        btn9.setBackground(Color.LIGHT_GRAY);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if (verificarBoton(evt)) {
            if (jugador == 1) {
                btn5.setText("O");
                jugador = 2;
            } else {
                btn5.setText("X");
                jugador = 1;
            }
        }
        verificarVictoria();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if (verificarBoton(evt)) {
            if (jugador == 1) {
                btn7.setText("O");
                jugador = 2;
            } else {
                btn7.setText("X");
                jugador = 1;
            }
        }
        verificarVictoria();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (verificarBoton(evt)) {
            if (jugador == 1) {
                btn1.setText("O");
                jugador = 2;
            } else {
                btn1.setText("X");
                jugador = 1;
            }
        }
        verificarVictoria();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (verificarBoton(evt)) {
            if (jugador == 1) {
                btn2.setText("O");
                jugador = 2;
            } else {
                btn2.setText("X");
                jugador = 1;
            }
        }
        verificarVictoria();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (verificarBoton(evt)) {
            if (jugador == 1) {
                btn3.setText("O");
                jugador = 2;
            } else {
                btn3.setText("X");
                jugador = 1;
            }
        }
        verificarVictoria();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (verificarBoton(evt)) {
            if (jugador == 1) {
                btn4.setText("O");
                jugador = 2;
            } else {
                btn4.setText("X");
                jugador = 1;
            }
        }
        verificarVictoria();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if (verificarBoton(evt)) {
            if (jugador == 1) {
                btn6.setText("O");
                jugador = 2;
            } else {
                btn6.setText("X");
                jugador = 1;
            }
        }
        verificarVictoria();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if (verificarBoton(evt)) {
            if (jugador == 1) {
                btn8.setText("O");
                jugador = 2;
            } else {
                btn8.setText("X");
                jugador = 1;
            }
        }
        verificarVictoria();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if (verificarBoton(evt)) {
            if (jugador == 1) {
                btn9.setText("O");
                jugador = 2;
            } else {
                btn9.setText("X");
                jugador = 1;
            }
        }
        verificarVictoria();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjugarActionPerformed
        // TODO add your handling code here:
        setearCampos();
    }//GEN-LAST:event_btnjugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnjugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private boolean verificarBoton(ActionEvent evt) {
        boolean b = false;
        if (evt.getActionCommand().equals("")) {
            b = true;
        }
        return b;
    }

    private void verificarVictoria() {
        /*
        1-2-3
        4-5-6
        7-8-9
        
        1-5-9
        7-5-3
        
        1-4-7
        2-5-8
        3-6-9
        
        */
        
       int op;
        if (btn1.getText().equals("O") && btn2.getText().equals("O") && btn3.getText().equals("O")) {
            btn1.setBackground(Color.GREEN);
            btn2.setBackground(Color.GREEN);
            btn3.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 1");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }

        if (btn4.getText().equals("O") && btn5.getText().equals("O") && btn6.getText().equals("O")) {
            btn4.setBackground(Color.GREEN);
            btn5.setBackground(Color.GREEN);
            btn6.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 1");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        if (btn7.getText().equals("O") && btn8.getText().equals("O") && btn9.getText().equals("O")) {
            btn7.setBackground(Color.GREEN);
            btn8.setBackground(Color.GREEN);
            btn9.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 1");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        
        if (btn1.getText().equals("O") && btn5.getText().equals("O") && btn9.getText().equals("O")) {
            btn1.setBackground(Color.GREEN);
            btn5.setBackground(Color.GREEN);
            btn9.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 1");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        
        if (btn7.getText().equals("O") && btn5.getText().equals("O") && btn3.getText().equals("O")) {
            btn7.setBackground(Color.GREEN);
            btn5.setBackground(Color.GREEN);
            btn3.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 1");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        if (btn1.getText().equals("O") && btn4.getText().equals("O") && btn7.getText().equals("O")) {
            btn1.setBackground(Color.GREEN);
            btn4.setBackground(Color.GREEN);
            btn7.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 1");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        
        if (btn2.getText().equals("O") && btn5.getText().equals("O") && btn8.getText().equals("O")) {
            btn2.setBackground(Color.GREEN);
            btn5.setBackground(Color.GREEN);
            btn8.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 1");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        if (btn3.getText().equals("O") && btn6.getText().equals("O") && btn9.getText().equals("O")) {
            btn3.setBackground(Color.GREEN);
            btn6.setBackground(Color.GREEN);
            btn9.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 1");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        
        
        
        //jugador 2
        if (btn1.getText().equals("X") && btn2.getText().equals("X") && btn3.getText().equals("X")) {
            btn1.setBackground(Color.GREEN);
            btn2.setBackground(Color.GREEN);
            btn3.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 2");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }

        if (btn4.getText().equals("X") && btn5.getText().equals("X") && btn6.getText().equals("X")) {
            btn4.setBackground(Color.GREEN);
            btn5.setBackground(Color.GREEN);
            btn6.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 2");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        if (btn7.getText().equals("X") && btn8.getText().equals("X") && btn9.getText().equals("X")) {
            btn7.setBackground(Color.GREEN);
            btn8.setBackground(Color.GREEN);
            btn9.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 2");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        
        if (btn1.getText().equals("X") && btn5.getText().equals("X") && btn9.getText().equals("X")) {
            btn1.setBackground(Color.GREEN);
            btn5.setBackground(Color.GREEN);
            btn9.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 2");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        
        if (btn7.getText().equals("X") && btn5.getText().equals("X") && btn3.getText().equals("X")) {
            btn7.setBackground(Color.GREEN);
            btn5.setBackground(Color.GREEN);
            btn3.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 2");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        if (btn1.getText().equals("X") && btn4.getText().equals("X") && btn7.getText().equals("X")) {
            btn1.setBackground(Color.GREEN);
            btn4.setBackground(Color.GREEN);
            btn7.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 2");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        
        if (btn2.getText().equals("X") && btn5.getText().equals("X") && btn8.getText().equals("X")) {
            btn2.setBackground(Color.GREEN);
            btn5.setBackground(Color.GREEN);
            btn8.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 2");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        if (btn3.getText().equals("X") && btn6.getText().equals("X") && btn9.getText().equals("X")) {
            btn3.setBackground(Color.GREEN);
            btn6.setBackground(Color.GREEN);
            btn9.setBackground(Color.GREEN);
            System.out.println("Victoria del jugador 2");
            op=JOptionPane.showConfirmDialog(null, "Jugar de nuevo?");
            if(op==0){
                setearCampos();
            }else{
                System.exit(0);
            }
        }
        
        
        
        

    }

    private void setearCampos() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        btn1.setText("");
        btn1.setBackground(Color.LIGHT_GRAY);
        btn2.setText("");
        btn2.setBackground(Color.LIGHT_GRAY);
        btn3.setText("");
        btn3.setBackground(Color.LIGHT_GRAY);
        btn4.setText("");
        btn4.setBackground(Color.LIGHT_GRAY);
        btn5.setText("");
        btn5.setBackground(Color.LIGHT_GRAY);
        btn6.setText("");
        btn6.setBackground(Color.LIGHT_GRAY);
        btn7.setText("");
        btn7.setBackground(Color.LIGHT_GRAY);
        btn8.setText("");
        btn8.setBackground(Color.LIGHT_GRAY);
        btn9.setText("");
        btn9.setBackground(Color.LIGHT_GRAY);
        
        
        
        
        
        
    }

}
